version: "3.3"

services:
  opsysdb:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=opsysdb
      - DB_USER=opsysuser
      - DB_PASS=opsyspass
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql

  backend:
    image: kajojepan/be_v2
    ports:
      - "8080:8080"
      #depends_on:
      # - opsysdb

  frontend:
    image: kajojepan/fe_v2
    ports:
      - "8082:8082"
    #links:
    #  - backend

volumes:
  data:
  logs: